name: Docker Build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Map branch to tag prefix
        id: branch_to_tag
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            echo "tag_prefix=prod" >> $GITHUB_OUTPUT
          elif [[ "$GITHUB_REF" == "refs/heads/dev" ]]; then
            echo "tag_prefix=dev" >> $GITHUB_OUTPUT
          else
            echo "tag_prefix=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ steps.branch_to_tag.outputs.tag_prefix }}-${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ steps.branch_to_tag.outputs.tag_prefix }}-latest
