name: ESLint

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
    paths:
      - '**.js'
      - '.eslintrc.*'
      - '.eslintignore'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/eslint.yml'
  pull_request:
    branches:
      - dev
    paths:
      - '**.js'
      - '.eslintrc.*'
      - '.eslintignore'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/eslint.yml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Copy default config files
        run: for file in conf/*.json.default; do cp "$file" "${file%.default}"; done

      - name: Run ESLint
        run: npm run lint
